# Generated by Django 4.2.4 on 2023-08-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=None, upload_to='imagens'),
            preserve_default=False,
        ),
    ]
